# Generated by Django 2.1.4 on 2019-06-09 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=100)),
                ('pin_code', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('phone', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('profile_pic', models.ImageField(upload_to='images/')),
                ('date_birth', models.DateTimeField()),
                ('permanent_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='profileApp.Address')),
                ('company_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comapny_address', to='profileApp.Address')),
                ('friends', models.ManyToManyField(to='profileApp.Profile')),
            ],
        ),
    ]
