# Generated by Django 2.1.4 on 2019-06-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0002_auto_20190610_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='profileApp.Profile'),
        ),
    ]
